name: 'Synopsys Intelligent Security Scan'
description: 'Initiate optimized SAST/SCA scans based on code changes and policy with filtered results for display in GitHub.'
author: 'DevSecOps Team @ Synopsys SIG'
branding:
  icon: 'shield'
  color: 'purple'
inputs:
  ioServerUrl:
    description: 'The server Host URL for Intelligent Scan Engine eg http://localhost:1111 or https://21b7.ngrok.io'
    required: true
  ioServerToken:
    description: 'The server password for Intelligent Scan Engine'
    required: true
  ioManifestUrl:
    description: 'HTTP URL to download IO Manifest file synopsys-io.yml'
    required: true
    default: 'https://sigdevsecops.blob.core.windows.net/intelligence-orchestration/2020.11/synopsys-io.yml'
  workflowServerUrl:
    description: 'The server Host URL for Intelligent Scan Workflow Engine eg http://localhost:1111 or https://21b7.ngrok.io'
    required: true
  workflowServerToken:
    description: 'The server password for Intelligent Scan Engine'
    required: true
  workflowVersion:
    description: 'The workflow jar version to retrieve for Intelligent Scan Engine'
    required: false
    default: 2020.12
  additionalWorkflowArgs:
    description: 'Additional arguments required for workflow engine arguments'
    required: true
  stage:
    description: 'Additional arguments required for workflow engine arguments'
    required: true
    default: 'IO' # This is either IO or WORKFLOW 

runs:
  using: 'node12'
  main: 'index.js'
